project_id = "pkrwpwomblbktqnqfjkw"

[functions.send-email-notification]
verify_jwt = false

[functions.check-reminders]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.check-badges]
verify_jwt = false

[functions.generate-recurring-meetings]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
